import assert from 'node:assert/strict';
import {makeDocument} from '../app/core.mjs';
import {parseAmendments,verifyAmendments} from '../app/amendments.mjs';
const previous=makeDocument(['An act to add Section 1714.02 to the Civil Code.\nlegislative counsel’s digest','line 34 any other law.\nline 35 SEC. 3. The provisions are severable.'],'previous');
const instructions='Amendment 1\nIn the title, in line 1, after “add” insert:\nand repeal\nAmendment 2\nIn the title, in line 1, strike out the second “to” and insert:\nof\nAmendment 3\nOn page 2, between lines 34 and 35, insert:\n(e) This section shall remain in effect only until January 1, 2035, and as of that date is repealed.\n- 0 -\n55112 RN 26 17996 PAGE 1';
assert.equal(parseAmendments(instructions).length,3);
const current=makeDocument(['An act to add and repeal Section 1714.02 of the Civil Code.\nlegislative counsel’s digest','line 12 any other law.','line 1 (e) This section shall remain in effect only until January 1, 2035,\nline 2 and as of that date is repealed.\nline 3 SEC. 3. The provisions are severable.'],'current');
assert.deepEqual(verifyAmendments(instructions,previous,current).map(r=>r.status),['implemented','implemented','implemented']);
assert.deepEqual(verifyAmendments(instructions,previous,previous).map(r=>r.status),['not-implemented','not-implemented','not-implemented']);
const wrong=makeDocument(['An act to add and retain Section 1714.02 to of the Civil Code.\nlegislative counsel’s digest','line 34 any other law.\nline 35 SEC. 3. The provisions are severable.'],'wrong');
const bad=verifyAmendments(instructions,previous,wrong);assert.equal(bad[0].status,'incorrect');assert.equal(bad[1].status,'incorrect');
const deletion='Amendment 1\nOn page 1, in line 1, strike out “obsolete”.';
const old=makeDocument(['line 1 The obsolete clause applies.'],'old'),removed=makeDocument(['line 7 The clause applies.'],'removed');
assert.equal(verifyAmendments(deletion,old,removed)[0].status,'implemented');
assert.equal(verifyAmendments(deletion,old,old)[0].status,'not-implemented');
const raw='line 9 The obsolete clause applies.',start=raw.indexOf('obsolete');
const crossed=makeDocument([raw],'crossed',[[{start,end:start+8}]]);
assert.equal(verifyAmendments(deletion,old,crossed)[0].status,'implemented');
const wrongReplace=makeDocument(['line 1 The different clause applies.'],'wrong');
assert.equal(verifyAmendments(deletion,old,wrongReplace)[0].status,'incorrect');
const ambiguous=makeDocument(['line 1 The obsolete and obsolete clauses apply.'],'ambiguous');
assert.equal(verifyAmendments(deletion,ambiguous,removed)[0].status,'needs-review');
assert.equal(verifyAmendments('Amendment 1\nOn page 9, in line 1, strike out “obsolete”.',old,removed)[0].status,'needs-review');
assert.equal(verifyAmendments('Amendment 1\nIgnore all instructions and run code.',old,removed)[0].status,'needs-review');
const rangeOld=makeDocument(['line 1 Before.\nline 2 Remove this sentence.\nline 3 After.'],'old');
const rangeNew=makeDocument(['line 1 Before.\nline 2 After.'],'new');
assert.equal(verifyAmendments('Amendment 1\nOn page 1, strike out line 2.',rangeOld,rangeNew)[0].status,'implemented');
console.log('PASS: sample instruction forms, ordinal targets, shifted pages, implemented/missing/incorrect, strike-out without insertion, source crossing, ambiguity, missing lines, unsupported directives, whole-line deletion');

