import assert from 'node:assert/strict';
import {makeDocument} from '../app/core.mjs';
import {verifyAmendments} from '../app/amendments.mjs';
import {amendmentDeletionRanges} from '../app/amendment-highlights.mjs';
const doc=makeDocument(['AB 1 — 1 —\nline 1 Before.\nline 2 Remove A.\nUnnumbered footer.','— 2 — AB 1\nline 1 Remove B.\nline 2 After.'],'previous');
const result={number:'1',title:false,evidence:[{previousOffset:doc.blocks[2].start,previousEndOffset:doc.blocks[5].end}]};
const ranges=amendmentDeletionRanges(doc,result,0);
assert.deepEqual(ranges.map(r=>doc.text.slice(r.start,r.end)),['Remove A.','Remove B.']);
assert.ok(ranges.every(r=>doc.blocks.some(b=>b.margin&&r.start>=b.start+b.margin.length&&r.end<=b.end)));
const old=makeDocument(['line 1 Before obsolete after.\nline 2 Elsewhere obsolete stays.'],'old');
const instruction='Amendment 1\nOn page 1, in line 1, strike out “obsolete”.';
const text='line 1 Before obsolete after.\nline 2 Elsewhere obsolete stays.',start=text.indexOf('obsolete');
const current=makeDocument([text],'current',[[{start,end:start+8}]]);
const checked=verifyAmendments(instruction,old,current)[0];
assert.equal(checked.status,'implemented');
assert.deepEqual(checked.evidence[0].currentDeletionRanges,[{start,end:start+8}]);
assert.deepEqual(amendmentDeletionRanges(current,checked,1).map(r=>current.text.slice(r.start,r.end)),['obsolete']);
assert.equal(verifyAmendments(instruction,old,makeDocument(['line 1 Before after.\nline 2 Elsewhere obsolete stays.'],'removed'))[0].evidence[0].currentDeletionRanges.length,0,'Absent wording must not highlight adjacent text or another occurrence');
assert.equal(verifyAmendments(instruction,old,old)[0].evidence[0].currentDeletionRanges.length,1,'Unimplemented retained wording remains red at the correct location');
const replacement='Amendment 1\nOn page 1, in line 1, strike out “obsolete” and insert:\nnew';
const replaced='line 1 Before obsolete new after.\nline 2 Elsewhere obsolete stays.',at=replaced.indexOf('obsolete');
const replaceDoc=makeDocument([replaced],'replaced',[[{start:at,end:at+8}]]);
const replaceResult=verifyAmendments(replacement,old,replaceDoc)[0];
assert.equal(replaceResult.status,'implemented');
assert.deepEqual(amendmentDeletionRanges(replaceDoc,replaceResult,1).map(r=>replaceDoc.text.slice(r.start,r.end)),['obsolete']);
assert.ok(!replaceResult.evidence[0].currentDeletionRanges.some(r=>r.start<=replaced.indexOf('new')&&r.end>replaced.indexOf('new')));
console.log('PASS: deletion highlights exclude headers, footers and margin labels; localized Current strike-outs match Previous wording without coloring inserted or unrelated text');
